# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYPN9Nqe3q9gWLuXvRXowRsM6sMHuu1B
"""

# STEP 1: Upload the file
from google.colab import files
uploaded = files.upload()

# STEP 2: Load and prepare the data
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the first 500 rows for speed
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name, sheet_name="mnist_test", nrows=500)

# Features and target
X = df.drop("label", axis=1)
y = df["label"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# STEP 3: Train a logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"✅ Accuracy: {accuracy * 100:.2f}%")
print("🔢 Sample Predictions:")
for true, pred in zip(y_test.values[:10], y_pred[:10]):
    print(f"Actual: {true} | Predicted: {pred}")